name: deploy mkdocs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
          pip install sphinx-autodoc-typehints pymunk
      - name: List directory structure
        run: |
          ls -R
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Add .nojekyll
        run: |
          touch docs/_build/html/.nojekyll
          touch docs/_build/.nojekyll
          touch docs/.nojekyll
          touch .nojekyll
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          publish_dir: _build/
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
