name: Upload Python Package

# on:
#   release:
#     types: [published]
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install poetry

    - name: Build the package
      run: |
        poetry check
        poetry build
    - name: Configure Poetry with PyPI token
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry config pypi-token.pypi $PYPI_API_TOKEN
    - name: Publish to PyPI
      run: |
        poetry publish
